name: Snyk Security Scan

on: [push, pull_request]

jobs:
  snyk:
    name: Run Snyk Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Snyk
        run: npm install -g snyk

      - name: Run Snyk Security Scan
        run: snyk test --all-projects
