name: Terraform Test

on:
  pull_request:
    branches:
      - main

jobs:
  tfsec:
    name: Run Terraform Static Analysis (tfsec)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Run Terraform Static Analysis
        run: terraform fmt -check=true -recursive
        continue-on-error: true

      - name: Install tfsec
        run: curl -L "$(curl -s https://api.github.com/repos/tfsec/tfsec/releases/latest | grep -o -E "https://.+?/tfsec-linux-amd64")" --output tfsec && chmod +x tfsec

      - name: Run tfsec
        run: ./tfsec
